apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    build.appstudio.redhat.com/multi-platform-config: hosts
  name: host-config
  namespace: multi-platform-controller
data:
  local-platforms: "\
    linux/amd64,\
    linux/x86_64,\
    local,\
    localhost,\
    "
  dynamic-platforms: "\
    linux-c2xlarge/amd64,\
    linux-c2xlarge/arm64,\
    linux-c4xlarge/amd64,\
    linux-c4xlarge/arm64,\
    linux-c8xlarge/amd64,\
    linux-c8xlarge/arm64,\
    linux-cxlarge/amd64,\
    linux-cxlarge/arm64,\
    linux-d160-cxlarge/arm64,\
    linux-d160-m2xlarge/amd64,\
    linux-d160-m2xlarge/arm64,\
    linux-d160/arm64,\
    linux-d200/ppc64le,\
    linux-d400-large/ppc64le,\
    linux-g6xlarge/amd64,\
    linux-large/ppc64le,\
    linux-large/s390x,\
    linux-largecpu/ppc64le,\
    linux-largecpu/s390x,\
    linux-m2xlarge/amd64,\
    linux-m2xlarge/arm64,\
    linux-m4xlarge/amd64,\
    linux-m4xlarge/arm64,\
    linux-m8xlarge/amd64,\
    linux-m8xlarge/arm64,\
    linux-mlarge/amd64,\
    linux-mlarge/arm64,\
    linux-mxlarge/amd64,\
    linux-mxlarge/arm64,\
    linux-root/amd64,\
    linux-root/arm64,\
    linux/amd64,\
    linux/arm64,\
    linux/ppc64le,\
    linux/s390x,\
    linux-large/ppc64le,\
    linux-extra-fast/amd64,\
    linux-fast/amd64,\
    linux-large/s390x,\
    linux/ppc64le,\
    linux-g4xlarge/amd64,\
    linux-d200/ppc64le,\
    "
  instance-tag: rhtap-prod

  dynamic.linux-arm64.type: aws
  dynamic.linux-arm64.region: us-east-1
  dynamic.linux-arm64.ami: ami-03d6a5256a46c9feb
  dynamic.linux-arm64.instance-type: m6g.large
  dynamic.linux-arm64.instance-tag: prod-arm64
  dynamic.linux-arm64.key-name: kflux-prd-multi-rh02-key-pair
  dynamic.linux-arm64.aws-secret: aws-account
  dynamic.linux-arm64.ssh-secret: aws-ssh-key
  dynamic.linux-arm64.security-group-id: sg-004ef1b7bc3ef1bca
  dynamic.linux-arm64.max-instances: "50"
  dynamic.linux-arm64.subnet-id: subnet-07a8bbf633e2bb187

  dynamic.linux-extra-fast-amd64.type: aws
  dynamic.linux-extra-fast-amd64.region: us-east-1
  dynamic.linux-extra-fast-amd64.ami: ami-026ebd4cfe2c043b2
  dynamic.linux-extra-fast-amd64.instance-type: c7a.12xlarge
  dynamic.linux-extra-fast-amd64.instance-tag: prod-amd64-extra-fast
  dynamic.linux-extra-fast-amd64.key-name: kflux-prd-multi-rh02-key-pair
  dynamic.linux-extra-fast-amd64.aws-secret: aws-account
  dynamic.linux-extra-fast-amd64.ssh-secret: aws-ssh-key
  dynamic.linux-extra-fast-amd64.security-group-id: sg-004ef1b7bc3ef1bca
  dynamic.linux-extra-fast-amd64.subnet-id: subnet-07a8bbf633e2bb187
  dynamic.linux-extra-fast-amd64.max-instances: "10"
  dynamic.linux-extra-fast-amd64.disk: "200"
  # dynamic.linux-extra-fast-amd64.iops: "16000"
  # dynamic.linux-extra-fast-amd64.throughput: "1000"

  dynamic.linux-root-amd64.type: aws
  dynamic.linux-root-amd64.region: us-east-1
  dynamic.linux-root-amd64.ami: ami-026ebd4cfe2c043b2
  dynamic.linux-root-amd64.instance-type: m6idn.2xlarge
  dynamic.linux-root-amd64.instance-tag: prod-amd64-root
  dynamic.linux-root-amd64.key-name: kflux-prd-multi-rh02-key-pair
  dynamic.linux-root-amd64.aws-secret: aws-account
  dynamic.linux-root-amd64.ssh-secret: aws-ssh-key
  dynamic.linux-root-amd64.security-group-id: sg-004ef1b7bc3ef1bca
  dynamic.linux-root-amd64.subnet-id: subnet-07a8bbf633e2bb187
  dynamic.linux-root-amd64.max-instances: "10"
  dynamic.linux-root-amd64.sudo-commands: "/usr/bin/podman"
  dynamic.linux-root-amd64.user-data: |-
    Content-Type: multipart/mixed; boundary="//"
    MIME-Version: 1.0

    --//
    Content-Type: text/cloud-config; charset="us-ascii"
    MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="cloud-config.txt"

    #cloud-config
    cloud_final_modules:
      - [scripts-user, always]

    --//
    Content-Type: text/x-shellscript; charset="us-ascii"
    MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="userdata.txt"

    #!/bin/bash -ex

    if lsblk -no FSTYPE /dev/nvme1n1 | grep -qE '\S'; then
     echo "File system exists on the disk."
    else
     echo "No file system found on the disk /dev/nvme1n1"
     mkfs -t xfs /dev/nvme1n1
    fi

    mount /dev/nvme1n1 /home

    if [ -d "/home/var-lib-containers" ]; then
     echo "Directory '/home/var-lib-containers' exist"
    else
     echo "Directory '/home/var-lib-containers' doesn't exist"
     mkdir -p /home/var-lib-containers /var/lib/containers
    fi

    mount --bind /home/var-lib-containers /var/lib/containers

    if [ -d "/home/var-tmp" ]; then
     echo "Directory '/home/var-tmp' exist"
    else
     echo "Directory '/home/var-tmp' doesn't exist"
     mkdir -p /home/var-tmp /var/tmp
    fi

    mount --bind /home/var-tmp /var/tmp

    if [ -d "/home/ec2-user" ]; then
    echo "ec2-user home exists"
    else
    echo "ec2-user home doesn't exist"
    mkdir -p /home/ec2-user/.ssh
    chown -R ec2-user /home/ec2-user
    fi

    sed -n 's,.*\(ssh-.*\s\),\1,p' /root/.ssh/authorized_keys > /home/ec2-user/.ssh/authorized_keys
    chown ec2-user /home/ec2-user/.ssh/authorized_keys
    chmod 600 /home/ec2-user/.ssh/authorized_keys
    chmod 700 /home/ec2-user/.ssh
    restorecon -r /home/ec2-user

    --//--

  dynamic.linux-large-s390x.type: ibmz
  dynamic.linux-large-s390x.ssh-secret: "ibm-ssh-key"
  dynamic.linux-large-s390x.secret: "ibm-api-key"
  dynamic.linux-large-s390x.vpc: "konflux-prod-multi-rh02"
  dynamic.linux-large-s390x.key: "konflux-s390x-root"
  dynamic.linux-large-s390x.subnet: "sn-20241213-02"
  dynamic.linux-large-s390x.image-id: "r006-20e160c3-58d7-4b3b-827f-9d7994b68095"
  dynamic.linux-large-s390x.region: "us-south-2"
  dynamic.linux-large-s390x.url: "https://us-south.iaas.cloud.ibm.com/v1"
  dynamic.linux-large-s390x.profile: "bz2-4x16"
  dynamic.linux-large-s390x.max-instances: "10"
  dynamic.linux-large-s390x.private-ip: "true"
  dynamic.linux-large-s390x.instance-tag: prod-s390x-large

  # test comment
  dynamic.linux-large-ppc64le.type: ibmp
  dynamic.linux-large-ppc64le.ssh-secret: "ibm-production-ppc64le-ssh-key"
  dynamic.linux-large-ppc64le.secret: "ibm-api-key"
  dynamic.linux-large-ppc64le.key: "prod-konflux-infra-external"
  dynamic.linux-large-ppc64le.image: "kflux-ppc-base-04-feb-2025"
  dynamic.linux-large-ppc64le.crn: "crn:v1:bluemix:public:power-iaas:dal12:a/8cfd5baa22024ab9822f1e9d4659a5e5:e08f6cb5-9d8c-4931-87c2-16580c2ffe0a::"
  dynamic.linux-large-ppc64le.url: "https://us-south.power-iaas.cloud.ibm.com"
  dynamic.linux-large-ppc64le.network: "54fc8e49-fcb0-4842-9802-405865f0597d"
  dynamic.linux-large-ppc64le.system: "e980"
  dynamic.linux-large-ppc64le.cores: "4"
  dynamic.linux-large-ppc64le.memory: "16"
  dynamic.linux-large-ppc64le.max-instances: "10"
  dynamic.linux-large-ppc64le.allocation-timeout: "1800"
  dynamic.linux-large-ppc64le.instance-tag: prod-ppc64le-large

  host.ppc1.address: "150.240.147.198"
  host.ppc1.platform: "linux/ppc64le"
  host.ppc1.user: "root"
  host.ppc1.secret: "ibm-ssh-key"
  host.ppc1.concurrency: "4"
